name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      theia-version:
        description: "Specify Theia version"
        required: true
        type: string
      deploy:
        description: "Push image to DockerHub"
        default: false
        required: false
        type: boolean

jobs:
  theia-alpine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate package.json
      run: node generatePackageJson.js ${{ inputs.theia-version }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ inputs.deploy == true }}
        tags: ${{ github.repository_owner }}/theia-alpine:latest
