name: Docker Image CI

on:
  pull_request:
#   schedule:
#     - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      theia-version:
        description: "Specify Theia version"
        default: "latest"
        required: false
        type: string
      deploy:
        description: "Push image to DockerHub"
        default: false
        required: false
        type: boolean

jobs:
  theia-alpine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Generate package.json
      id: versions
      run: node generatePackageJson.js ${{ inputs.theia-version || 'next' }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        build-args: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.deploy == true || github.event_name == 'schedule' }}
        tags: |
          ${{ github.repository_owner }}/theia-alpine:${{ steps.versions.outputs.THEIA_VERSION }}
          ${{ contains(inputs.theia-version, 'community') && format('{0}/theia-alpine:community', github.repository_owner) || '' }}
          ${{ inputs.theia-version == 'latest' && format('{0}/theia-alpine:latest', github.repository_owner) || '' }}
